version: 0.2

phases:

  install:
    commands:
      - apt -y update
      - apt -y install awscli texlive-full

  build:
    commands:
      - pdflatex -output-directory static resume/resume.tex

  post_build:
    commands:
      - rm static/resume.out static/resume.aux static/resume.log
      - aws cloudformation describe-stacks --stack-name weblog --query 'Stacks[0].Outputs[?OutputKey==`Bucket`].OutputValue' --output text > bucket
      - aws s3 sync --delete static/ s3://$(cat bucket)
      - aws cloudformation describe-stacks --stack-name weblog --query 'Stacks[0].Outputs[?OutputKey==`Distribution`].OutputValue' --output text > distribution
      - aws cloudfront create-invalidation --distribution-id $(cat distribution) --paths '*'

artifacts:
  discard-paths: yes
  files:
    - static/resume.pdf
    - static/error.html
    - static/index.html
    - static/robots.txt
