version: 0.2

phases:

  install:
    commands:
      - apt -y update
      - apt -y install awscli texlive-full

  pre_build:
    commands:
      - aws cloudformation describe-stack-resources --stack-name weblog --query 'StackResources[?LogicalResourceId==`Bucket`].PhysicalResourceId' --output text > bucket

  build:
    commands:
      - pdflatex resume/resume.tex

  post_build:
    commands: []

artifacts:
  discard-paths: yes
  files:
    - bucket
    - resume.pdf
    - static/error.html
    - static/favicon.ico
    - static/index.html
    - static/robots.txt
