AWSTemplateFormatVersion: '2010-09-09'

Conditions: {}

Description: Weblog

Mappings: {}

Metadata: {}

Outputs: {}

Parameters: {}

Resources:

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html

  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - dylanscott.com.au
        CustomErrorResponses:
          - ErrorCode: 400
            ResponseCode: 400
            ResponsePagePath: /error.html
          - ErrorCode: 403
            ResponseCode: 403
            ResponsePagePath: /error.html
          - ErrorCode: 404
            ResponseCode: 404
            ResponsePagePath: /error.html
          - ErrorCode: 405
            ResponseCode: 405
            ResponsePagePath: /error.html
          - ErrorCode: 414
            ResponseCode: 414
            ResponsePagePath: /error.html
          - ErrorCode: 500
            ResponseCode: 500
            ResponsePagePath: /error.html
          - ErrorCode: 501
            ResponseCode: 501
            ResponsePagePath: /error.html
          - ErrorCode: 502
            ResponseCode: 502
            ResponsePagePath: /error.html
          - ErrorCode: 503
            ResponseCode: 503
            ResponsePagePath: /error.html
          - ErrorCode: 504
            ResponseCode: 504
            ResponsePagePath: /error.html
        DefaultCacheBehavior:
          Compress: true
          ForwardedValues:
            QueryString: false
          TargetOriginId: diogenes
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: true
        Origins:
        - DomainName:
            !GetAtt
            - Bucket
            - DomainName
          Id: diogenes
          S3OriginConfig: {}
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:584259415401:certificate/2e1c3909-cfe1-48f3-b1ba-38c7b50d78d5
          SslSupportMethod: sni-only

Outputs:

  Bucket:
    Description: Cloudfront disribution origin bucket
    Value: !Ref Bucket

  Distribution:
    Description: Cloudfront distribution
    Value: !Ref Distribution
